name: lancaai
description: "Letras de Rita Lee aprofundadas com Gemini"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_chat_ui: ^1.6.12
  flutter_gemini: ^2.0.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  restart_app: ^1.2.1
  flutter_svg: ^2.0.10+1
  universal_html: ^2.2.4
  flutter_chat_types: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gemini.png
    - assets/rita.jpg
