List<String> songLyrics = [
  // Mania de você
  "Meu bem, você me dá água na boca\nVestindo fantasias, tirando a roupa\nMolhada de suor de tanto a gente se beijar\nDe tanto imaginar loucuras\nA gente faz amor por telepatia\nNo chão, no mar, na lua, na melodia\nMania de você\nDe tanto a gente se beijar\nDe tanto imaginar loucuras\nNada melhor do que não fazer nada\nSó pra deitar e rolar com você\nNada melhor do que não fazer nada\nSó pra deitar e rolar com você\nMeu bem, você me dá água na boca\nVestindo fantasias, tirando a roupa\nMolhada de suor de tanto a gente se beijar\nDe tanto imaginar loucuras\nA gente faz amor por telepatia\nNo chão, no mar, na lua, na melodia\nMania de você\nDe tanto a gente se beijar\nDe tanto imaginar loucuras\nNada melhor do que não fazer nada\nSó pra deitar e rolar com você\nNada melhor do que não fazer nada\nSó pra deitar e rolar com você\nCom você, com você\nNada melhor, nada melhor\nDo que não fazer nada\nNada, nada melhor do que não fazer nada\nSó pra deitar e... com você\nRolar, rolar, rolar, rolar com você\nRolar, rolar, rolar, rolar com você\nRolar, rolar, rolar, rolar com você",
  // Colombina
  "Se você voltar pra mim,\nJuro para sempre ser arlequim\nE brincar o carnaval\nViver uma fantasia real\nSou um triste pierrot mal-amado\nMestre-sala desacompanhado\nUm bufão no salão a cantar...\nColombina, hey!\nSeja minha menina, só minha\nBailarina, hey!\nMandarina da China, rainha\nQuero ser seu rei!\nUm rei momo, sem dono, sem trono\nAbram alas pro amor!\nMinha vida sem você\nÉ uma canção de amor tão clichê\nO meu \"bem-me-quer\" não quis\nFez de mim um folião infeliz",
  // Agora só falta você
  "Um belo dia resolvi mudar\nE fazer tudo o que eu queria fazer\nMe libertei daquela vida vulgar\nQue eu levava estando junto a você\nE em tudo o que eu faço\nExiste um porquê\nEu sei que eu nasci\nSei que eu nasci pra saber\nE fui andando sem pensar em voltar\nE sem ligar pro que me aconteceu\nUm belo dia vou lhe telefonar\nPra lhe dizer que aquele sonho cresceu\nNo ar que eu respiro\nEu sinto prazer\nDe ser quem eu sou\nDe estar onde estou\nAgora só falta você\nUm belo dia resolvi mudar\nE fazer tudo o que eu queria fazer\nMe libertei daquela vida vulgar\nQue eu levava estando junto a você\nE em tudo o que eu faço\nExiste um porquê\nEu sei que eu nasci\nSei que eu nasci pra saber\nSaber o que\nE fui andando sem pensar em voltar\nE sem ligar pro que me aconteceu\nUm belo dia vou lhe telefonar\nPra lhe dizer que aquele sonho cresceu\nNo ar que eu respiro\nEu sinto prazer\nDe ser quem eu sou\nDe estar onde estou\nAgora só falta você\nAgora só falta você\nAgora só falta você\nAgora só falta você",
  // Caso sério
  "Eu fico pensando em nós dois\nCada um na sua, perdidos na cidade nua\nEmpapuçados de amor\nNuma noite de verão\nAi, que coisa boa\nÀ meia-luz, a sós, à toa\nVocê e eu somos um\nCaso sério\nAo som de um bolero\nDose dupla\nRomânticos de Cuba Libre\nMisto-quente\nSanduíche de gente\nEu fico pensando em nós dois\nCada um na sua, perdidos na cidade nua\nEmpapuçados de amor\nNuma noite de verão\nAi, que coisa boa\nÀ meia-luz, a sós, à toa\nVocê e eu somos um\nCaso sério\nAo som de um bolero\nDose dupla\nRomânticos de Cuba Libre\nMisto-quente (quente quente quente)\nSanduíche de gente\nVocê e eu somos um\nCaso sério\nAo som de um bolero\nDose dupla\nRomânticos de Cuba Libre\nMisto-quente (quente)\nSanduíche de gente",
  // Desculpe o auê
  "Desculpe o auê\nEu não queria magoar você\nFoi ciúme, sim\nFiz greve de fome, guerrilhas, motim\nPerdi a cabeça, esqueça\nDesculpe o auê\nEu não queria magoar você\nFoi ciúme, sim\nFiz greve de fome, guerrilhas, motim\nPerdi a cabeça, esqueça\nDa próxima vez eu me mando\nQue se dane meu jeito inseguro\nNosso amor vale tanto\nPor você vou roubar os anéis de Saturno\nDa próxima vez eu me mando\nQue se dane meu jeito inseguro\nNosso amor vale tanto\nPor você vou roubar os anéis de Saturno",
  // Ovelha negra
  "Levava uma vida sossegada\nGostava de sombra e água fresca\nMeu Deus quanto tempo eu passei\nSem saber\nUh uh\nFoi quando meu pai me disse filha\nVocê é a ovelha negra da família\nAgora é hora de você assumir\nUh uh e sumir\nBaby baby\nNão adianta chamar\nQuando alguém está perdido\nProcurando se encontrar\nBaby baby\nNão vale a pena esperar, oh não\nTire isso da cabeça\nE ponha o resto no lugar\nAh ah ah tchu tchu tchu tchu\nNão, ah ah ah tchu tchu tchu tchu\nNão\nLevava uma vida sossegada\nGostava de sombra e água fresca\nMeu Deus quanto tempo eu passei\nSem saber\nUh uh\nFoi quando meu pai me disse filha\nVocê é a ovelha negra da família\nAgora é hora de você assumir\nUh uh e sumir\nBaby baby\nNão adianta chamar\nQuando alguém está perdido\nProcurando se encontrar\nBaby baby\nNão vale a pena esperar, oh não\nTire isso da cabeça\nE ponha o resto no lugar\nAh ah ah tchu tchu tchu tchu\nNão, ovelha negra da família\nTchu tchu tchu tchu tchu (não vai mais voltar)\nNão, vai sumir",
  // Lança perfume
  "Lança menina, lança todo esse perfume\nDesbaratina\nNão dá pra ficar imune\nAo teu amor que tem cheiro de coisa maluca\nVem cá, meu bem\nMe descola um carinho\nEu sou neném\nSó sossego com um beijinho\nVê se me dá o prazer de ter prazer comigo\nMe aqueça\nMe vira de ponta cabeça\nMe faz de gato e sapato\nMe deixa de quatro no ato\nMe enche de amor, de amor\nLança, lança perfume, oh\nLança, lança perfume, oh\nLança, lança, lança perfume\nLança perfume\nLança, lança, lança perfume\nLança perfume\nLança",
  // Ando meio desligado
  "Ando meio desligado\nEu nem sinto meus pés no chão\nOlho e não vejo nada\nEu só penso se você me quer\nEu nem vejo a hora de lhe dizer\nAquilo tudo que eu decorei\nE depois o beijo que eu já sonhei\nVocê vai sentir, mas...\nPor favor, não leve a mal\nEu só quero que você me queira\nNão leve a mal",
  // Fora da lei
  "Cidade nua, noite neon\nGata de rua faz ron-ron ao luar\nSaio da cama, pulo a janela\nNinguém como ela, ao luar\nMia, arranha o céu\nMia, lua de mel ao léu, well\nDois gatos pingados fora da lei\nEla é a rainha, eu o rei\nFarra no telhado fora da lei\nTudo bem\nSobe e desce muros fora da lei\nEla sai por onde entrei\nGritos e sussurros fora da lei\nCidade nua, faz serenata\nBeijo na boca, vira-lata, de lixo\nAmor de bicho, paixão maluca\nCama de gato, Kama Sutra ao luar",
  // Baila comigo
  "Se Deus quiser\nUm dia eu quero ser índio\nViver pelado, pintado de verde\nNum eterno domingo\nSer um bicho preguiça, espantar turista\nE tomar banho de sol, banho de sol, banho de sol, sol\nSe Deus quiser um dia acabo voando\nTão banal, assim como um pardal\nMeio de contrabando\nDesviar de estilingue, deixar que me xinguem\nE tomar banho de sol, banho de sol, banho de sol, sol\nBaila comigo, como se baila na tribo\nBaila comigo, lá no meu esconderijo, ai\nBaila comigo, como se baila na tribo, oh\nBaila, baila comigo, lá no meu esconderijo, ai ai ai\nSe Deus quiser um dia eu viro semente\nE quando a chuva molhar o jardim\nAh, eu fico contente\nE na primavera vou brotar na terra\nE tomar banho de sol, banho de sol, banho de sol, sol\nSe Deus quiser\num dia eu morro bem velha\nNa hora \"H\" quando a bomba estourar quero ver da janela\nE entrar no pacote de camarote\nE tomar banho de sol, banho de sol, banho de sol, banho de sol\nBaila comigo, como se baila na tribo\nBaila, baila comigo, lá no meu esconderijo, ai, oh\nBaila comigo, como se baila na tribo\nBaila, baila comigo, lá no meu esconderijo, ai, ai\nSol, Sol, Sol\nE tomar banho de sol, banho de sol, banho de sol, banho de sol, ah\nBaila comigo, como se baila na tribo\nBaila, baila comigo, lá no meu esconderijo, ai, ai, ai\nBaila comigo, como se baila na tribo\nBaila, baila comigo, lá no meu esconderijo, ai, ai\nAi corazón\nBaila comigo, como se baila na tribo, te lo juro\nBaila, baila comigo, lá no meu esconderijo, ai, ai, ai\nAi, yo quiero un besito del Nelson\nAi, el Nelson\nAi, el Nelson\nAcércate más e vamos a bailar, ah\nLá no meu esconderijo, ai, ai, ai"
];
