List<Map<String, String>> songData = [
  {
    'Música': 'Mania de você',
    'Álbum': 'Rita Lee',
    'Artista': 'Rita Lee',
    'Ano': '1979',
    'Gênero': 'MPB, Pop, Rock',
  },
  {
    'Música': 'Colombina',
    'Álbum': 'As segundas intenções do manual prático',
    'Artista': 'Ed Motta, Rita Lee',
    'Ano': '2000',
    'Gênero': 'MPB, Pop, Rock',
  },
  {
    'Música': 'Agora só falta você',
    'Álbum': 'Fruto Proibido',
    'Artista': 'Rita Lee',
    'Ano': '1975',
    'Gênero': 'Pop, MPB',
  },
  {
    'Música': 'Caso sério',
    'Álbum': 'Rita Lee',
    'Artista': 'Rita Lee, Roberto de Carvalho',
    'Ano': '1980',
    'Gênero': 'MPB',
  },
  {
    'Música': 'Desculpe o auê',
    'Álbum': 'Bombom',
    'Artista': 'Rita Lee, Roberto de Carvalho',
    'Ano': '1983',
    'Gênero': 'MPB',
  },
  {
    'Música': 'Ovelha negra',
    'Álbum': 'Fruto Proibido',
    'Artista': 'Rita Lee',
    'Ano': '1975',
    'Gênero': 'Pop, MPB',
  },
  {
    'Música': 'Lança perfume',
    'Álbum': 'Rita Lee',
    'Artista': 'Rita Lee',
    'Ano': '1980',
    'Gênero': 'MPB, Pop',
  },
  {
    'Música': 'Ando meio desligado',
    'Álbum': 'Rita Lee em Bossa \'n Roll',
    'Artista': 'Rita Lee',
    'Ano': '1991',
    'Gênero': 'MPB, Pop, Rock',
  },
  {
    'Música': 'Fora da lei',
    'Álbum': 'Manual prático para festas, bailes e afins',
    'Artista': 'Ed Motta, Rita Lee',
    'Ano': '1997',
    'Gênero': 'Soul, funk, pop',
  },
  {
    'Música': 'Baila comigo',
    'Álbum': 'Rita Lee',
    'Artista': 'Rita Lee',
    'Ano': '1980',
    'Gênero': 'MPB, Pop',
  },
];
